[project]
name = "hformat"
requires-python = ">3.9"
authors = [
    {
        name = "Herve Habonimana", email = "habonimanah@gmail.com"
    },
]

dependencies = [
    "click",
    "colorama",
    "pandas"
]